############# English navigation ##############

# main menu
[[main]]
name = "FJ2 Tech Inc"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Services"
hasChildren = true

[[main]]
parent = "Services"
name = "Machine Learning"
url = "blog/"
weight = 1

[[main]]
parent = "Services"
name = "Application Development"
url = "authors/"
weight = 2

[[main]]
parent = "Services"
name = "Project Management"
url = "contact/"
weight = 3

[[main]]
name = "About"
url = "about/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
